services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      PORT: 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    container_name: db

    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./.kursdbdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DOCKER_PORT}

volumes:
  kursdbdata: